int bitAnd(int, int);
int test_bitAnd(int, int);
int minusOne();
int test_minusOne();
int tmax();
int test_tmax();
int copyLSB(int);
int test_copyLSB(int);
int evenBits(int);
int test_evenBits();
int isEqual(int, int);
int test_isEqual(int, int);
int negate(int);
int test_negate(int);
int bitMask(int, int);
int test_bitMask(int, int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int isPositive(int);
int test_isPositive(int);
int reverseBytes(int);
int test_reverseBytes(int);
int isPower2(int);
int test_isPower2(int);
